language: dart
sudo: required
dart:
  - stable
  - beta
  - dev
addons:
  chrome: stable
before_script:
  - cd repo_support
script:
  - dart pub get
  - dart run tool/travis.dart
matrix:
  allow_failures:
    - dart: dev