name: tekartik_app_node_build_menu
description: Build menu for nodes app (google cloud and aliyun)
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  args: ">=2.6.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

dev_dependencies:
  # Needed direct dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  lints: ">=5.0.0"
  test: ">=1.24.0"

executables:
  nbm: nbm
resolution: workspace
