name: tekartik_app_node_build_menu
description: Build menu for nodes app (google cloud and aliyun)
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path:
  args:
  dev_build: '>=0.16.5-6'
  process_run:
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

dev_dependencies:
  # Needed direct dependencies
  build_runner:
  build_web_compilers:
  lints: '>=2.0.0'
  test: '>=1.16.0'

dependency_overrides:
  tekartik_app_node_build:
    path: ../app_build

executables:
  nbm: nbm
