name: tekartik_app_node_utils
description: Node utilities.
version: 0.2.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.7.0
  stack_trace:
  js:
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: platform_node
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils
      ref: dart2_3
    version: '>=0.1.1'
  process_run:

dev_dependencies:
  test: ^1.14.4
  # Needed direct dependencies
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_app_node_build_menu:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build_menu
      ref: dart2_3
    version: '>=0.1.0'
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3
dependency_overrides:
  tekartik_app_node_build:
    path: ../app_build
  tekartik_app_node_build_menu:
    path: ../app_build_menu