name: tekartik_app_node_utils
description: Node utilities.
version: 0.2.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  stack_trace:
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform
      ref: dart3a
    version: '>=0.2.1'
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: platform_node
      ref: dart3a
    version: '>=0.2.1'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
    version: '>=0.2.1'
  process_run: ">=1.2.1+1"
  tekartik_js_utils_interop:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils_interop

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  test: ">=1.24.0"
  # Needed direct dependencies
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
  tekartik_app_node_build_menu:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build_menu
      ref: dart3a
    version: '>=0.1.0'
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

resolution: workspace
