name: tekartik_app_node_utils
description: Node utilities.
version: 0.2.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: null_safety
    version: '>=0.2.1'
  tekartik_platform_node:
    git:
      url: git://github.com/tekartik/common_node.dart
      path: platform_node
      ref: null_safety
    version: '>=0.2.1'
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_io
      ref: null_safety
    version: '>=0.2.1'
  tekartik_js_utils:
    git:
      url: git://github.com/tekartik/js_utils.dart
      path: js_utils
      ref: null_safety
    version: '>=0.1.1'
  process_run:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  # Needed direct dependencies
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: null_safety
    version: '>=0.1.0'
  build_runner:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety

dependency_overrides:
  # tekartik_app_node_build:
  #   path: ../app_build
