name: tekartik_app_node_build
description: Node build dependencies
version: 0.3.5
publish_to: none
deploy_to: none

environment:
  sdk: ^3.8.0

dependencies:
  path: ">=1.9.0"
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  # needed node dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.1.0'
  tekartik_common_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/common_build

dev_dependencies:
  build_test:
resolution: workspace

# dependency_overrides:
  # tekartik_lints:
  #  path: ../../../tekartik/common.dart/packages/lints
