name: tekartik_app_node_build
description: Node build dependencies
version: 0.3.3
publish_to: none
deploy_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  pedantic: ^1.9.0
  test: ^1.14.4
  process_run: '>=0.11.0+2'
  dev_test: '>=0.13.3-dev.3'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3

dev_dependencies:
  build_test:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.1.0'