name: tekartik_app_node_build
description: Node build dependencies
version: 0.2.5
publish_to: none
deploy_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  tekartik_app_node_utils:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart2
    version: '>=0.1.0'
  path: ^1.7.0

  pedantic: ^1.9.0
  test: ^1.14.4
  process_run: '>=0.11.0+2'
  dev_test: '>=0.13.3-dev.3'

dev_dependencies:
  build_runner:
  build_node_compilers:
  build_test:

dependency_overrides:
  tekartik_app_node_utils:
    path: ../node_utils