name: tekartik_app_node_build
description: Node build dependencies
version: 0.3.5
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: '>=1.7.0'
  test: '>=1.14.4'
  process_run: '>=1.0.0+3'
  dev_build: '>=1.0.0'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.1.0'

dev_dependencies:
  build_test:

# dependency_overrides:
  # tekartik_lints:
  #  path: ../../../tekartik/common.dart/packages/lints
